name: update-repo-docs

on:
  workflow_dispatch:
  schedule:
    - cron: '5 4 * * *'
  push:
    branches:
      - develop
      
jobs:
  update-repo-docs:
    uses: fortify/shared-doc-resources/.github/workflows/update-repo-docs.yml@main